let colors= [
     { code: '#5fb5dd', tag:  'bike'},
     {code: '#feb948', tag:  'bills'},
     {code: '#4b91d7', tag:  'buss Fair'},
     {code: '#727ce7', tag:  'business'},
     {code: '#a18ef7', tag:  'cable'},
     {code: '#98c8de', tag:  'car'},
     {code: '#54d0b4', tag:  'cash'},
     {code: '#a4aef0', tag:  'cloths'},
     {code: '#c8765c', tag:  'coffee'},
     {code: '#dc8382', tag:  'cigarettes'},
     {code: '#cfa595', tag:  'cookies'},
     {code: '#8ca8b5', tag:  'cycle'},
     {code: '#8eb794', tag:  'courier'},
     {code: '#34e49d', tag:  'dely care'},
     {code: '#4caf50', tag:  'dining'},
     {code: '#20c454', tag:  'dinner'},
     {code: '#ff8a65', tag:  'disko'},
     {code: '#c4c2b3', tag:  'donation'},
     {code: '#f76c63', tag:  'drinks'},
     {code: '#ffcc00', tag:  'education'},
     {code: '#9bb8d9', tag:  'electricity'},
     {code: '#fb8c00', tag:  'electronics'},
     {code: '#a2b6cd', tag:  'emi'},
     {code: '#ff677a', tag:  'entertatment'},
     {code: '#6ad218', tag:  'fast food'},
     {code: '#49a2d7', tag:  'finance'},
     {code: '#ff9501', tag:  'food drink'},
     {code: '#5fb5dd', tag:  'bike'},
     {code: '#24c936', tag:  'fruit'},
     {code: '#4db2e6', tag:  'games'},
     {code: '#f88f9a', tag:  'gift'},
     {code: '#75b030', tag:  'Grocery'},
     {code: '#fbc02d', tag:  'gold'},
     {code: '#24cea8', tag:  'gym'},
     {code: '#3edfbb', tag:  'health'},
     {code: '#d07cde', tag:  'otel'},
     {code: '#4cda64', tag:  'household'},
     {code: '#b388ff', tag:  'icecream'},
     {code: '#00b8d4', tag:  'insurance'},
     {code: '#90adcf', tag:  'interst'},
     {code: '#d9cb18', tag:  'investments'},
     {code: '#ffd548', tag:  'jewellery'},
     {code: '#4fc3f7', tag:  'kids'},
     {code: '#51b7ff', tag:  'oans'},
     {code: '#b19995', tag:  'maiddriver'},
     {code: '#b69b91', tag:  'maintanance'},
     {code: '#ff4546', tag:  'medcial'},
     {code: '#bda8c6', tag:  'miscellaneous'},

     {code: '#ea707f', tag:  'mobile'},
     {code: '#ff4a61', tag:  'music'},
     {code: '#ff4a61', tag:  'mutual funds'},
     {code: '#c3bcc4', tag:  'office'},
     {code: '#bfb6c3', tag:  'others'},

     {code: '#f17685', tag:  'pasties'},
     {code: '#f277a8', tag:  'personal care'},
     {code: '#cc99fe', tag:  'Pets'},
     {code: '#e77067', tag:  'postoffice'},
     {code: '#c7c758', tag:  'prepaid wallet'},
     {code: '#a5a1a6', tag:  'printout and scanning'},
     {code: '#f56480', tag:  'pub'},
     {code: '#76c537', tag:  'rent'},
     {code: '#72a5d6', tag:  'Salon'},
     {code: '#8abc62', tag:  'savings'},
     {code: '#d4d1b4', tag:  'Shoes'},
     {code: '#ff677a', tag:  'shopping'},
     {code: '#fbc576', tag:  'spa'},
     {code: '#e1d368', tag:  'Stationery'},
     {code: '#28c5b8', tag:  'Stocks'},
     {code: '#8abfe6', tag:  'tax'},
     {code: '#e4d40d', tag:  'taxi'},
     {code: '#ff80ab', tag:  'toys'},
     {code: '#ea8b55', tag:  'transaport'},
     {code: '#5ac8fb', tag:  'travel'},
     {code: '#8bdad4', tag:  'UPI'},
     {code: '#00cccb', tag:  'vacation'},
     {code: '#42a5f5', tag:  'water'},
     {code: '#e3e017', tag: 'gas'}

];

export default colors;
